# Generated by Selenium IDE
import shelve
from selenium import webdriver
from classselenium.base import Base

class TestDemo1(Base):


    def test_csdn(self):
        # shelve 小型数据，对象持久化保存方法
        db = shelve.open('mydb/logincookies')
        cookies = db['cookie']
        db.close()

        self.driver.get("https://www.csdn.net/")
        for cookie in cookies:
            if 'expiry' in cookie.keys():
                cookie.pop('expiry')
            self.driver.add_cookie(cookie)

        self.driver.get("https://www.csdn.net/")
        self.driver.find_element_by_css_selector('.userLogin:nth-child(6) .login_img').click()
        windows = self.driver.window_handles
        self.driver.switch_to.window(windows[1])
        self.driver.find_element_by_css_selector('.modify-img').click()
        self.driver.find_element_by_css_selector('.vicp-hint').click()
        self.driver.find_element_by_css_selector('.input:nth-child(4)').type('C:\fakepath\20180829174746.jpg')
        self.driver.find_element_by_link_text('上传并保存').click()







