# Generated by Selenium IDE
import shelve
from selenium import webdriver
from classselenium.base import Base

class TestDemo1(Base):


    def test_csdn(self):
        # shelve 小型数据，对象持久化保存方法
        db = shelve.open('mydb/logincookies')
        cookies = db['cookie']
        db.close()

        self.driver.get("https://www.csdn.net/")
        for cookie in cookies:
            if 'expiry' in cookie.keys():
                cookie.pop('expiry')
            self.driver.add_cookie(cookie)

        self.driver.get("https://www.csdn.net/")
        self.driver.find_element_by_css_selector('.userLogin:nth-child(6) .login_img').click()
        windows = self.driver.window_handles
        self.driver.switch_to.window(windows[1])
        img_position = self.driver.find_element_by_xpath('//*[@id="app"]/div/header/div/div/div[1]/div/img')
        self.action.move_to_element(img_position).perform()

        self.driver.find_element_by_css_selector('.modify-img').click()
        self.driver.find_element_by_xpath('//*[@id="app"]/div/header/div/div[2]/div/div/div[2]/div[1]/span[1]').send_keys('D:/123.JPG')
        # self.driver.find_element_by_link_text('上传并保存').click()







